services:
  warotickets:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL:-https://api.warotickets.com}
        - NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL:-https://warotickets.com}
        - NODE_ENV=${NODE_ENV:-production}
    container_name: warotickets-${APP_ENV:-prod}
    ports:
      - "${HOST_PORT:-3003}:3003"
    env_file:
      - .env.${APP_ENV:-prod}
    volumes:
      - nuxt-data:/app/storage
    networks:
      - warolabs-network
    restart: unless-stopped

networks:
  warolabs-network:
    external: true

volumes:
  nuxt-data:
