services:
  warotickets:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warotickets-${APP_ENV:-prod}
    ports:
      - "${HOST_PORT:-3003}:3003"
    env_file:
      - .env.${APP_ENV:-prod}
    volumes:
      - nuxt-data:/app/storage
    networks:
      - warolabs-network
    restart: unless-stopped

networks:
  warolabs-network:
    external: true

volumes:
  nuxt-data:
